name: Deploy test/ to GitHub Pages
on:
  push:
    branches: [main]
concurrency:
  group: deploy-test-to-github-pages
  cancel-in-progress: true
permissions: write-all
jobs:
  deploy-test-to-github-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.actions-deploy-pages.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm pack --dry-run
      - run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<meta http-equiv="refresh" content="0; url=test/basic.html" />' >> index.html
          echo '<script>location.replace("test/basic.html")</script>' >> index.html
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
      - id: actions-deploy-pages
        uses: actions/deploy-pages@v1
