# This GitHub action is triggered by pushes to the main branch. It deploys the
# "test" folder to GitHub Pages. The concurrency group is unique to the specific
# branch pushed. In-progress jobs will be canceled. The action requires write
# permissions on the repository. The environment variable "github-pages" is set
# to the output page_url of the step "actions-deploy-pages" and it runs on an
# ubuntu-latest environment. The steps include: checking out the repository,
# setting up node, installing dependencies, dry-run packaging, creating an
# index.html file for redirecting to test/basic.html, configuring pages,
# uploading the artifact, and deploying to GitHub Pages.
name: Deploy test/ to GitHub Pages
on:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
      - "*.js"
      - "*.json"
      - .github/workflows/deploy-test-to-github-pages.yml
concurrency:
  group: deploy-test-to-github-pages
  cancel-in-progress: true
permissions: write-all
jobs:
  deploy-test-to-github-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.actions-deploy-pages.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm pack --dry-run
      - run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<meta http-equiv="refresh" content="0; url=test/basic.html" />' >> index.html
          echo '<script>location.replace("test/basic.html")</script>' >> index.html
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
      - id: actions-deploy-pages
        uses: actions/deploy-pages@v1
